events { 
    worker_connections 1024; 
}

http {

    # WebSockets start as a standard HTTP request and then "Upgrade" to a persistent connection. 
    # The map directive tells Nginx how to set the Connection header based on whether the client (your browser) is asking for an upgrade.
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    upstream keycloakServer {
        server keycloak_admin_console:8080;

        zone keycloak_http 64k;
    }

    server {
            listen 80;
            listen [::]:80;

            server_name localhost;

            location /health {
                    access_log off;
                    return 200 "healthy\n";
            }

            location / {
                    proxy_pass http://keycloakServer;
                    proxy_http_version 1.1;

                    # Forwarded headers for modern Keycloak
                    proxy_set_header Host $host:8080;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_set_header X-Forwarded-Host $host;
                    proxy_set_header X-Forwarded-Port $server_port;
                    proxy_set_header X-Forwarded-Port 8080;

                    # Upgrade support (WebSockets, admin console live features)
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection $connection_upgrade;

                    proxy_buffer_size          128k;
                    proxy_buffers              4 256k;
                    proxy_busy_buffers_size    256k;

                    # Buffers and timeouts — tune for your traffic profile
                    proxy_connect_timeout 5s;
                    proxy_read_timeout 90s;
                    proxy_send_timeout 60s;
                    proxy_buffering on;

                # proxy_redirect      http://keycloakServer; # http://YOUR_DOMAIN_NAME_HERE;
            }
    }
}