name: Build-AWS-Infrastructure-with-Terraform 

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  build_aws_infrastructure_with_terraform:
    name: Build AWS Infrastructure with Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: tf_enviournments

    permissions:
      id-token: write # This permission setting enables the workflow to request and use a JSON Web Token (JWT) from GitHub's OpenID Connect (OIDC) provider. 
      contents: read # This permission grants the GITHUB_TOKEN read-only access to the repository's contents (for actions/checkout@v2). 
      actions: read      # Required to download artifacts from other runs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      # Establish an AWS Account
      - name: Configure AWS Credentials (OIDC for Terraform)
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          # role-session-name: GitHub-OIDC-TERRAFORM
      
      ##
      # Setup AWS resources using Terraform 
      ##
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false
      #
      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init
      #
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      #
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      #
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
      
      - name: Export EC2 instance ID for deploy job
        id: ec2-id
        run: echo "instance_id=$(terraform output -raw ec2_instance_id)" >> $GITHUB_OUTPUT

      - name: Create aws EC2 instance ID into json file 
        run: |
          printf '{
            "ec2_instance_id": "${{ steps.ec2-id.outputs.instance_id }}",  
            "aws_region": "${{secrets.AWS_REGION}}"
            }' >> ec2_instance.json

      - name: Upload JSON Data with AWS EC2 Instance ID
        uses: actions/upload-artifact@v6
        with:
          name: ec2_instance.json
          path: .

      - run:  |
          pwd
          ls  -ltra
      - name: List files in the repository (tree)
        run: tree .